### PR TITLE
Structure

### PR DESCRIPTION
**Pull request by dargmuesli**
Hey @m-kyle,

I've added a README explaining the idea behind this repository and normalized the branch structure.

Branches are supposed to allow testing of new experimental features while keeping the main code base untouched. I think braches "desktop" and "mobile" do not comply with this idea, therefore I merged them.

Good day,
Jonas Thelemann

### CODE REVIEW

**Comment by dargmuesli** [comment]
After merging this PR you can delete branch "mobile" and create a new branch "master" on "desktop". Then, in the repository's branch settings set "master" as main branch and delete "desktop". That'll fix it.

**Comment by dargmuesli** [comment]
The only issue I've got are four new wallpapers with the same names as wallpapers already present in this repository. For example two wallpapers with the name "Mesa Arch, Utah 1920x1080.jpg". The wallpapers are photos of the same object from different angles / taken on different dates. How do you want to manage those files?

**Comment by m-kyle** [comment]
I've updated my SpotBright for new images and the mesa arch image with a sunset was renamed `240066343561386151image_fullscreen_001_landscape.jpg`.

**Comment by m-kyle** [comment]
I'll merge this PR then fix the branches.

**Pull request merged**
